name: PR watcher  

on:
  pull_request:
    types: [closed]

jobs:
  staging:
    runs-on: ubuntu-latest
    needs: [watch-pr]
    steps:
      - name: staging
        run: |
          echo "hola staging"
    
